
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Security Group for EC2 machines to be made available for SSH connection 
      GroupName: ExternallyConnectableEC2Machines
      SecurityGroupEgress: 
        - Egress
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0